# Generated by Django 5.0.3 on 2024-03-28 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Published',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_additional', models.TextField(blank=True, null=True)),
                ('text_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('type_cover', models.TextField(blank=True, null=True)),
                ('date_of_create', models.IntegerField(default=0)),
                ('isbn', models.TextField(blank=True)),
                ('count_of_pages', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('age_restrictions', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField(default=0)),
                ('cost_per_one', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.TextField(blank=True, null=True)),
                ('additional_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.additionalgenre')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.published')),
            ],
        ),
    ]
