# Generated by Django 5.0.3 on 2024-03-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_create',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
