# Generated by Django 5.0.3 on 2024-03-29 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_date_of_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalgenre',
            name='text_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='additional_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.additionalgenre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.published'),
        ),
    ]
