# Generated by Django 5.0.3 on 2024-04-08 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_count_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_on_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.genre'),
        ),
    ]
