# Generated by Django 5.0.3 on 2024-04-08 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_count_on_stock_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='additional_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.additionalgenre'),
        ),
    ]
