# Generated by Django 5.0.3 on 2024-04-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_additional_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='count_on_stock',
            field=models.IntegerField(default=5),
        ),
    ]
