# Generated by Django 5.0.3 on 2024-04-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_additionalgenre_id_alter_author_id_and_more'),
        ('order', '0004_alter_address_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Helper',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('all_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
